
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserPositions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserPositions
 * 
 */
export type UserPositionsModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPositionsPayload>

export type AggregateUserPositions = {
  _count: UserPositionsCountAggregateOutputType | null
  _avg: UserPositionsAvgAggregateOutputType | null
  _sum: UserPositionsSumAggregateOutputType | null
  _min: UserPositionsMinAggregateOutputType | null
  _max: UserPositionsMaxAggregateOutputType | null
}

export type UserPositionsAvgAggregateOutputType = {
  size: number | null
  avgPrice: number | null
  initialValue: number | null
  currentValue: number | null
  cashPnl: number | null
  percentPnl: number | null
  totalBought: number | null
  realizedPnl: number | null
  percentRealizedPnl: number | null
  curPrice: number | null
  outcomeIndex: number | null
}

export type UserPositionsSumAggregateOutputType = {
  size: number | null
  avgPrice: number | null
  initialValue: number | null
  currentValue: number | null
  cashPnl: number | null
  percentPnl: number | null
  totalBought: number | null
  realizedPnl: number | null
  percentRealizedPnl: number | null
  curPrice: number | null
  outcomeIndex: number | null
}

export type UserPositionsMinAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  icon: string | null
  proxyWallet: string | null
  assets: string | null
  conditionId: string | null
  size: number | null
  avgPrice: number | null
  initialValue: number | null
  currentValue: number | null
  cashPnl: number | null
  percentPnl: number | null
  totalBought: number | null
  realizedPnl: number | null
  percentRealizedPnl: number | null
  curPrice: number | null
  redeemable: boolean | null
  mergeable: boolean | null
  eventSlug: string | null
  outcome: string | null
  outcomeIndex: number | null
  oppositeOutcome: string | null
  oppositeAsset: string | null
  endDate: Date | null
  negativeRisk: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserPositionsMaxAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  icon: string | null
  proxyWallet: string | null
  assets: string | null
  conditionId: string | null
  size: number | null
  avgPrice: number | null
  initialValue: number | null
  currentValue: number | null
  cashPnl: number | null
  percentPnl: number | null
  totalBought: number | null
  realizedPnl: number | null
  percentRealizedPnl: number | null
  curPrice: number | null
  redeemable: boolean | null
  mergeable: boolean | null
  eventSlug: string | null
  outcome: string | null
  outcomeIndex: number | null
  oppositeOutcome: string | null
  oppositeAsset: string | null
  endDate: Date | null
  negativeRisk: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserPositionsCountAggregateOutputType = {
  id: number
  title: number
  slug: number
  icon: number
  proxyWallet: number
  assets: number
  conditionId: number
  size: number
  avgPrice: number
  initialValue: number
  currentValue: number
  cashPnl: number
  percentPnl: number
  totalBought: number
  realizedPnl: number
  percentRealizedPnl: number
  curPrice: number
  redeemable: number
  mergeable: number
  eventSlug: number
  outcome: number
  outcomeIndex: number
  oppositeOutcome: number
  oppositeAsset: number
  endDate: number
  negativeRisk: number
  created_at: number
  updated_at: number
  _all: number
}


export type UserPositionsAvgAggregateInputType = {
  size?: true
  avgPrice?: true
  initialValue?: true
  currentValue?: true
  cashPnl?: true
  percentPnl?: true
  totalBought?: true
  realizedPnl?: true
  percentRealizedPnl?: true
  curPrice?: true
  outcomeIndex?: true
}

export type UserPositionsSumAggregateInputType = {
  size?: true
  avgPrice?: true
  initialValue?: true
  currentValue?: true
  cashPnl?: true
  percentPnl?: true
  totalBought?: true
  realizedPnl?: true
  percentRealizedPnl?: true
  curPrice?: true
  outcomeIndex?: true
}

export type UserPositionsMinAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  proxyWallet?: true
  assets?: true
  conditionId?: true
  size?: true
  avgPrice?: true
  initialValue?: true
  currentValue?: true
  cashPnl?: true
  percentPnl?: true
  totalBought?: true
  realizedPnl?: true
  percentRealizedPnl?: true
  curPrice?: true
  redeemable?: true
  mergeable?: true
  eventSlug?: true
  outcome?: true
  outcomeIndex?: true
  oppositeOutcome?: true
  oppositeAsset?: true
  endDate?: true
  negativeRisk?: true
  created_at?: true
  updated_at?: true
}

export type UserPositionsMaxAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  proxyWallet?: true
  assets?: true
  conditionId?: true
  size?: true
  avgPrice?: true
  initialValue?: true
  currentValue?: true
  cashPnl?: true
  percentPnl?: true
  totalBought?: true
  realizedPnl?: true
  percentRealizedPnl?: true
  curPrice?: true
  redeemable?: true
  mergeable?: true
  eventSlug?: true
  outcome?: true
  outcomeIndex?: true
  oppositeOutcome?: true
  oppositeAsset?: true
  endDate?: true
  negativeRisk?: true
  created_at?: true
  updated_at?: true
}

export type UserPositionsCountAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  proxyWallet?: true
  assets?: true
  conditionId?: true
  size?: true
  avgPrice?: true
  initialValue?: true
  currentValue?: true
  cashPnl?: true
  percentPnl?: true
  totalBought?: true
  realizedPnl?: true
  percentRealizedPnl?: true
  curPrice?: true
  redeemable?: true
  mergeable?: true
  eventSlug?: true
  outcome?: true
  outcomeIndex?: true
  oppositeOutcome?: true
  oppositeAsset?: true
  endDate?: true
  negativeRisk?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type UserPositionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPositions to aggregate.
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPositions to fetch.
   */
  orderBy?: Prisma.UserPositionsOrderByWithRelationInput | Prisma.UserPositionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserPositionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserPositions
  **/
  _count?: true | UserPositionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserPositionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserPositionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserPositionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserPositionsMaxAggregateInputType
}

export type GetUserPositionsAggregateType<T extends UserPositionsAggregateArgs> = {
      [P in keyof T & keyof AggregateUserPositions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserPositions[P]>
    : Prisma.GetScalarType<T[P], AggregateUserPositions[P]>
}




export type UserPositionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserPositionsWhereInput
  orderBy?: Prisma.UserPositionsOrderByWithAggregationInput | Prisma.UserPositionsOrderByWithAggregationInput[]
  by: Prisma.UserPositionsScalarFieldEnum[] | Prisma.UserPositionsScalarFieldEnum
  having?: Prisma.UserPositionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserPositionsCountAggregateInputType | true
  _avg?: UserPositionsAvgAggregateInputType
  _sum?: UserPositionsSumAggregateInputType
  _min?: UserPositionsMinAggregateInputType
  _max?: UserPositionsMaxAggregateInputType
}

export type UserPositionsGroupByOutputType = {
  id: string
  title: string | null
  slug: string | null
  icon: string | null
  proxyWallet: string | null
  assets: string | null
  conditionId: string | null
  size: number | null
  avgPrice: number | null
  initialValue: number | null
  currentValue: number | null
  cashPnl: number | null
  percentPnl: number | null
  totalBought: number | null
  realizedPnl: number | null
  percentRealizedPnl: number | null
  curPrice: number | null
  redeemable: boolean
  mergeable: boolean
  eventSlug: string | null
  outcome: string | null
  outcomeIndex: number | null
  oppositeOutcome: string | null
  oppositeAsset: string | null
  endDate: Date | null
  negativeRisk: boolean
  created_at: Date
  updated_at: Date
  _count: UserPositionsCountAggregateOutputType | null
  _avg: UserPositionsAvgAggregateOutputType | null
  _sum: UserPositionsSumAggregateOutputType | null
  _min: UserPositionsMinAggregateOutputType | null
  _max: UserPositionsMaxAggregateOutputType | null
}

type GetUserPositionsGroupByPayload<T extends UserPositionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserPositionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserPositionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserPositionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserPositionsGroupByOutputType[P]>
      }
    >
  >



export type UserPositionsWhereInput = {
  AND?: Prisma.UserPositionsWhereInput | Prisma.UserPositionsWhereInput[]
  OR?: Prisma.UserPositionsWhereInput[]
  NOT?: Prisma.UserPositionsWhereInput | Prisma.UserPositionsWhereInput[]
  id?: Prisma.StringFilter<"UserPositions"> | string
  title?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  slug?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  icon?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  proxyWallet?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  assets?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  conditionId?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  size?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  avgPrice?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  initialValue?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  currentValue?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  cashPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  percentPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  totalBought?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  realizedPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  percentRealizedPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  curPrice?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  redeemable?: Prisma.BoolFilter<"UserPositions"> | boolean
  mergeable?: Prisma.BoolFilter<"UserPositions"> | boolean
  eventSlug?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  outcome?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  outcomeIndex?: Prisma.IntNullableFilter<"UserPositions"> | number | null
  oppositeOutcome?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  oppositeAsset?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  endDate?: Prisma.DateTimeNullableFilter<"UserPositions"> | Date | string | null
  negativeRisk?: Prisma.BoolFilter<"UserPositions"> | boolean
  created_at?: Prisma.DateTimeFilter<"UserPositions"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserPositions"> | Date | string
}

export type UserPositionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  proxyWallet?: Prisma.SortOrderInput | Prisma.SortOrder
  assets?: Prisma.SortOrderInput | Prisma.SortOrder
  conditionId?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  avgPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  initialValue?: Prisma.SortOrderInput | Prisma.SortOrder
  currentValue?: Prisma.SortOrderInput | Prisma.SortOrder
  cashPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  percentPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  totalBought?: Prisma.SortOrderInput | Prisma.SortOrder
  realizedPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  curPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemable?: Prisma.SortOrder
  mergeable?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  oppositeOutcome?: Prisma.SortOrderInput | Prisma.SortOrder
  oppositeAsset?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  negativeRisk?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserPositionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserPositionsWhereInput | Prisma.UserPositionsWhereInput[]
  OR?: Prisma.UserPositionsWhereInput[]
  NOT?: Prisma.UserPositionsWhereInput | Prisma.UserPositionsWhereInput[]
  title?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  slug?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  icon?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  proxyWallet?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  assets?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  conditionId?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  size?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  avgPrice?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  initialValue?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  currentValue?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  cashPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  percentPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  totalBought?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  realizedPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  percentRealizedPnl?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  curPrice?: Prisma.FloatNullableFilter<"UserPositions"> | number | null
  redeemable?: Prisma.BoolFilter<"UserPositions"> | boolean
  mergeable?: Prisma.BoolFilter<"UserPositions"> | boolean
  eventSlug?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  outcome?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  outcomeIndex?: Prisma.IntNullableFilter<"UserPositions"> | number | null
  oppositeOutcome?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  oppositeAsset?: Prisma.StringNullableFilter<"UserPositions"> | string | null
  endDate?: Prisma.DateTimeNullableFilter<"UserPositions"> | Date | string | null
  negativeRisk?: Prisma.BoolFilter<"UserPositions"> | boolean
  created_at?: Prisma.DateTimeFilter<"UserPositions"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserPositions"> | Date | string
}, "id">

export type UserPositionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  proxyWallet?: Prisma.SortOrderInput | Prisma.SortOrder
  assets?: Prisma.SortOrderInput | Prisma.SortOrder
  conditionId?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  avgPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  initialValue?: Prisma.SortOrderInput | Prisma.SortOrder
  currentValue?: Prisma.SortOrderInput | Prisma.SortOrder
  cashPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  percentPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  totalBought?: Prisma.SortOrderInput | Prisma.SortOrder
  realizedPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrderInput | Prisma.SortOrder
  curPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemable?: Prisma.SortOrder
  mergeable?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  oppositeOutcome?: Prisma.SortOrderInput | Prisma.SortOrder
  oppositeAsset?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  negativeRisk?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.UserPositionsCountOrderByAggregateInput
  _avg?: Prisma.UserPositionsAvgOrderByAggregateInput
  _max?: Prisma.UserPositionsMaxOrderByAggregateInput
  _min?: Prisma.UserPositionsMinOrderByAggregateInput
  _sum?: Prisma.UserPositionsSumOrderByAggregateInput
}

export type UserPositionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserPositionsScalarWhereWithAggregatesInput | Prisma.UserPositionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserPositionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserPositionsScalarWhereWithAggregatesInput | Prisma.UserPositionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserPositions"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  slug?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  icon?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  proxyWallet?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  assets?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  conditionId?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  size?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  avgPrice?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  initialValue?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  currentValue?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  cashPnl?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  percentPnl?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  totalBought?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  realizedPnl?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  percentRealizedPnl?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  curPrice?: Prisma.FloatNullableWithAggregatesFilter<"UserPositions"> | number | null
  redeemable?: Prisma.BoolWithAggregatesFilter<"UserPositions"> | boolean
  mergeable?: Prisma.BoolWithAggregatesFilter<"UserPositions"> | boolean
  eventSlug?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  outcome?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  outcomeIndex?: Prisma.IntNullableWithAggregatesFilter<"UserPositions"> | number | null
  oppositeOutcome?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  oppositeAsset?: Prisma.StringNullableWithAggregatesFilter<"UserPositions"> | string | null
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"UserPositions"> | Date | string | null
  negativeRisk?: Prisma.BoolWithAggregatesFilter<"UserPositions"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"UserPositions"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"UserPositions"> | Date | string
}

export type UserPositionsCreateInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  proxyWallet?: string | null
  assets?: string | null
  conditionId?: string | null
  size?: number | null
  avgPrice?: number | null
  initialValue?: number | null
  currentValue?: number | null
  cashPnl?: number | null
  percentPnl?: number | null
  totalBought?: number | null
  realizedPnl?: number | null
  percentRealizedPnl?: number | null
  curPrice?: number | null
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: string | null
  outcome?: string | null
  outcomeIndex?: number | null
  oppositeOutcome?: string | null
  oppositeAsset?: string | null
  endDate?: Date | string | null
  negativeRisk?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserPositionsUncheckedCreateInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  proxyWallet?: string | null
  assets?: string | null
  conditionId?: string | null
  size?: number | null
  avgPrice?: number | null
  initialValue?: number | null
  currentValue?: number | null
  cashPnl?: number | null
  percentPnl?: number | null
  totalBought?: number | null
  realizedPnl?: number | null
  percentRealizedPnl?: number | null
  curPrice?: number | null
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: string | null
  outcome?: string | null
  outcomeIndex?: number | null
  oppositeOutcome?: string | null
  oppositeAsset?: string | null
  endDate?: Date | string | null
  negativeRisk?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserPositionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assets?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  avgPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  initialValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currentValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  cashPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalBought?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  realizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentRealizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  curPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mergeable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  oppositeOutcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oppositeAsset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  negativeRisk?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPositionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assets?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  avgPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  initialValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currentValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  cashPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalBought?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  realizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentRealizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  curPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mergeable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  oppositeOutcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oppositeAsset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  negativeRisk?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPositionsCreateManyInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  proxyWallet?: string | null
  assets?: string | null
  conditionId?: string | null
  size?: number | null
  avgPrice?: number | null
  initialValue?: number | null
  currentValue?: number | null
  cashPnl?: number | null
  percentPnl?: number | null
  totalBought?: number | null
  realizedPnl?: number | null
  percentRealizedPnl?: number | null
  curPrice?: number | null
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: string | null
  outcome?: string | null
  outcomeIndex?: number | null
  oppositeOutcome?: string | null
  oppositeAsset?: string | null
  endDate?: Date | string | null
  negativeRisk?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserPositionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assets?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  avgPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  initialValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currentValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  cashPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalBought?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  realizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentRealizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  curPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mergeable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  oppositeOutcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oppositeAsset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  negativeRisk?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPositionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assets?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  avgPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  initialValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currentValue?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  cashPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalBought?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  realizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  percentRealizedPnl?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  curPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mergeable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  oppositeOutcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oppositeAsset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  negativeRisk?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserPositionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  assets?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  size?: Prisma.SortOrder
  avgPrice?: Prisma.SortOrder
  initialValue?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  cashPnl?: Prisma.SortOrder
  percentPnl?: Prisma.SortOrder
  totalBought?: Prisma.SortOrder
  realizedPnl?: Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrder
  curPrice?: Prisma.SortOrder
  redeemable?: Prisma.SortOrder
  mergeable?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  oppositeOutcome?: Prisma.SortOrder
  oppositeAsset?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  negativeRisk?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserPositionsAvgOrderByAggregateInput = {
  size?: Prisma.SortOrder
  avgPrice?: Prisma.SortOrder
  initialValue?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  cashPnl?: Prisma.SortOrder
  percentPnl?: Prisma.SortOrder
  totalBought?: Prisma.SortOrder
  realizedPnl?: Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrder
  curPrice?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
}

export type UserPositionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  assets?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  size?: Prisma.SortOrder
  avgPrice?: Prisma.SortOrder
  initialValue?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  cashPnl?: Prisma.SortOrder
  percentPnl?: Prisma.SortOrder
  totalBought?: Prisma.SortOrder
  realizedPnl?: Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrder
  curPrice?: Prisma.SortOrder
  redeemable?: Prisma.SortOrder
  mergeable?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  oppositeOutcome?: Prisma.SortOrder
  oppositeAsset?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  negativeRisk?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserPositionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  assets?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  size?: Prisma.SortOrder
  avgPrice?: Prisma.SortOrder
  initialValue?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  cashPnl?: Prisma.SortOrder
  percentPnl?: Prisma.SortOrder
  totalBought?: Prisma.SortOrder
  realizedPnl?: Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrder
  curPrice?: Prisma.SortOrder
  redeemable?: Prisma.SortOrder
  mergeable?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  oppositeOutcome?: Prisma.SortOrder
  oppositeAsset?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  negativeRisk?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserPositionsSumOrderByAggregateInput = {
  size?: Prisma.SortOrder
  avgPrice?: Prisma.SortOrder
  initialValue?: Prisma.SortOrder
  currentValue?: Prisma.SortOrder
  cashPnl?: Prisma.SortOrder
  percentPnl?: Prisma.SortOrder
  totalBought?: Prisma.SortOrder
  realizedPnl?: Prisma.SortOrder
  percentRealizedPnl?: Prisma.SortOrder
  curPrice?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type UserPositionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  proxyWallet?: boolean
  assets?: boolean
  conditionId?: boolean
  size?: boolean
  avgPrice?: boolean
  initialValue?: boolean
  currentValue?: boolean
  cashPnl?: boolean
  percentPnl?: boolean
  totalBought?: boolean
  realizedPnl?: boolean
  percentRealizedPnl?: boolean
  curPrice?: boolean
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: boolean
  outcome?: boolean
  outcomeIndex?: boolean
  oppositeOutcome?: boolean
  oppositeAsset?: boolean
  endDate?: boolean
  negativeRisk?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userPositions"]>

export type UserPositionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  proxyWallet?: boolean
  assets?: boolean
  conditionId?: boolean
  size?: boolean
  avgPrice?: boolean
  initialValue?: boolean
  currentValue?: boolean
  cashPnl?: boolean
  percentPnl?: boolean
  totalBought?: boolean
  realizedPnl?: boolean
  percentRealizedPnl?: boolean
  curPrice?: boolean
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: boolean
  outcome?: boolean
  outcomeIndex?: boolean
  oppositeOutcome?: boolean
  oppositeAsset?: boolean
  endDate?: boolean
  negativeRisk?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userPositions"]>

export type UserPositionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  proxyWallet?: boolean
  assets?: boolean
  conditionId?: boolean
  size?: boolean
  avgPrice?: boolean
  initialValue?: boolean
  currentValue?: boolean
  cashPnl?: boolean
  percentPnl?: boolean
  totalBought?: boolean
  realizedPnl?: boolean
  percentRealizedPnl?: boolean
  curPrice?: boolean
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: boolean
  outcome?: boolean
  outcomeIndex?: boolean
  oppositeOutcome?: boolean
  oppositeAsset?: boolean
  endDate?: boolean
  negativeRisk?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userPositions"]>

export type UserPositionsSelectScalar = {
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  proxyWallet?: boolean
  assets?: boolean
  conditionId?: boolean
  size?: boolean
  avgPrice?: boolean
  initialValue?: boolean
  currentValue?: boolean
  cashPnl?: boolean
  percentPnl?: boolean
  totalBought?: boolean
  realizedPnl?: boolean
  percentRealizedPnl?: boolean
  curPrice?: boolean
  redeemable?: boolean
  mergeable?: boolean
  eventSlug?: boolean
  outcome?: boolean
  outcomeIndex?: boolean
  oppositeOutcome?: boolean
  oppositeAsset?: boolean
  endDate?: boolean
  negativeRisk?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type UserPositionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "slug" | "icon" | "proxyWallet" | "assets" | "conditionId" | "size" | "avgPrice" | "initialValue" | "currentValue" | "cashPnl" | "percentPnl" | "totalBought" | "realizedPnl" | "percentRealizedPnl" | "curPrice" | "redeemable" | "mergeable" | "eventSlug" | "outcome" | "outcomeIndex" | "oppositeOutcome" | "oppositeAsset" | "endDate" | "negativeRisk" | "created_at" | "updated_at", ExtArgs["result"]["userPositions"]>

export type $UserPositionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserPositions"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string | null
    slug: string | null
    icon: string | null
    proxyWallet: string | null
    assets: string | null
    conditionId: string | null
    size: number | null
    avgPrice: number | null
    initialValue: number | null
    currentValue: number | null
    cashPnl: number | null
    percentPnl: number | null
    totalBought: number | null
    realizedPnl: number | null
    percentRealizedPnl: number | null
    curPrice: number | null
    redeemable: boolean
    mergeable: boolean
    eventSlug: string | null
    outcome: string | null
    outcomeIndex: number | null
    oppositeOutcome: string | null
    oppositeAsset: string | null
    endDate: Date | null
    negativeRisk: boolean
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["userPositions"]>
  composites: {}
}

export type UserPositionsGetPayload<S extends boolean | null | undefined | UserPositionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload, S>

export type UserPositionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserPositionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserPositionsCountAggregateInputType | true
  }

export interface UserPositionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserPositions'], meta: { name: 'UserPositions' } }
  /**
   * Find zero or one UserPositions that matches the filter.
   * @param {UserPositionsFindUniqueArgs} args - Arguments to find a UserPositions
   * @example
   * // Get one UserPositions
   * const userPositions = await prisma.userPositions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserPositionsFindUniqueArgs>(args: Prisma.SelectSubset<T, UserPositionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserPositions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserPositionsFindUniqueOrThrowArgs} args - Arguments to find a UserPositions
   * @example
   * // Get one UserPositions
   * const userPositions = await prisma.userPositions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserPositionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserPositionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPositions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsFindFirstArgs} args - Arguments to find a UserPositions
   * @example
   * // Get one UserPositions
   * const userPositions = await prisma.userPositions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserPositionsFindFirstArgs>(args?: Prisma.SelectSubset<T, UserPositionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPositions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsFindFirstOrThrowArgs} args - Arguments to find a UserPositions
   * @example
   * // Get one UserPositions
   * const userPositions = await prisma.userPositions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserPositionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserPositionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserPositions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserPositions
   * const userPositions = await prisma.userPositions.findMany()
   * 
   * // Get first 10 UserPositions
   * const userPositions = await prisma.userPositions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userPositionsWithIdOnly = await prisma.userPositions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserPositionsFindManyArgs>(args?: Prisma.SelectSubset<T, UserPositionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserPositions.
   * @param {UserPositionsCreateArgs} args - Arguments to create a UserPositions.
   * @example
   * // Create one UserPositions
   * const UserPositions = await prisma.userPositions.create({
   *   data: {
   *     // ... data to create a UserPositions
   *   }
   * })
   * 
   */
  create<T extends UserPositionsCreateArgs>(args: Prisma.SelectSubset<T, UserPositionsCreateArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserPositions.
   * @param {UserPositionsCreateManyArgs} args - Arguments to create many UserPositions.
   * @example
   * // Create many UserPositions
   * const userPositions = await prisma.userPositions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserPositionsCreateManyArgs>(args?: Prisma.SelectSubset<T, UserPositionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserPositions and returns the data saved in the database.
   * @param {UserPositionsCreateManyAndReturnArgs} args - Arguments to create many UserPositions.
   * @example
   * // Create many UserPositions
   * const userPositions = await prisma.userPositions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserPositions and only return the `id`
   * const userPositionsWithIdOnly = await prisma.userPositions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserPositionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserPositionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserPositions.
   * @param {UserPositionsDeleteArgs} args - Arguments to delete one UserPositions.
   * @example
   * // Delete one UserPositions
   * const UserPositions = await prisma.userPositions.delete({
   *   where: {
   *     // ... filter to delete one UserPositions
   *   }
   * })
   * 
   */
  delete<T extends UserPositionsDeleteArgs>(args: Prisma.SelectSubset<T, UserPositionsDeleteArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserPositions.
   * @param {UserPositionsUpdateArgs} args - Arguments to update one UserPositions.
   * @example
   * // Update one UserPositions
   * const userPositions = await prisma.userPositions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserPositionsUpdateArgs>(args: Prisma.SelectSubset<T, UserPositionsUpdateArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserPositions.
   * @param {UserPositionsDeleteManyArgs} args - Arguments to filter UserPositions to delete.
   * @example
   * // Delete a few UserPositions
   * const { count } = await prisma.userPositions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserPositionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserPositionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserPositions
   * const userPositions = await prisma.userPositions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserPositionsUpdateManyArgs>(args: Prisma.SelectSubset<T, UserPositionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPositions and returns the data updated in the database.
   * @param {UserPositionsUpdateManyAndReturnArgs} args - Arguments to update many UserPositions.
   * @example
   * // Update many UserPositions
   * const userPositions = await prisma.userPositions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserPositions and only return the `id`
   * const userPositionsWithIdOnly = await prisma.userPositions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserPositionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserPositionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserPositions.
   * @param {UserPositionsUpsertArgs} args - Arguments to update or create a UserPositions.
   * @example
   * // Update or create a UserPositions
   * const userPositions = await prisma.userPositions.upsert({
   *   create: {
   *     // ... data to create a UserPositions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserPositions we want to update
   *   }
   * })
   */
  upsert<T extends UserPositionsUpsertArgs>(args: Prisma.SelectSubset<T, UserPositionsUpsertArgs<ExtArgs>>): Prisma.Prisma__UserPositionsClient<runtime.Types.Result.GetResult<Prisma.$UserPositionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsCountArgs} args - Arguments to filter UserPositions to count.
   * @example
   * // Count the number of UserPositions
   * const count = await prisma.userPositions.count({
   *   where: {
   *     // ... the filter for the UserPositions we want to count
   *   }
   * })
  **/
  count<T extends UserPositionsCountArgs>(
    args?: Prisma.Subset<T, UserPositionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserPositionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserPositionsAggregateArgs>(args: Prisma.Subset<T, UserPositionsAggregateArgs>): Prisma.PrismaPromise<GetUserPositionsAggregateType<T>>

  /**
   * Group by UserPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPositionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserPositionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserPositionsGroupByArgs['orderBy'] }
      : { orderBy?: UserPositionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserPositionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserPositionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserPositions model
 */
readonly fields: UserPositionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserPositions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserPositionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserPositions model
 */
export interface UserPositionsFieldRefs {
  readonly id: Prisma.FieldRef<"UserPositions", 'String'>
  readonly title: Prisma.FieldRef<"UserPositions", 'String'>
  readonly slug: Prisma.FieldRef<"UserPositions", 'String'>
  readonly icon: Prisma.FieldRef<"UserPositions", 'String'>
  readonly proxyWallet: Prisma.FieldRef<"UserPositions", 'String'>
  readonly assets: Prisma.FieldRef<"UserPositions", 'String'>
  readonly conditionId: Prisma.FieldRef<"UserPositions", 'String'>
  readonly size: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly avgPrice: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly initialValue: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly currentValue: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly cashPnl: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly percentPnl: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly totalBought: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly realizedPnl: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly percentRealizedPnl: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly curPrice: Prisma.FieldRef<"UserPositions", 'Float'>
  readonly redeemable: Prisma.FieldRef<"UserPositions", 'Boolean'>
  readonly mergeable: Prisma.FieldRef<"UserPositions", 'Boolean'>
  readonly eventSlug: Prisma.FieldRef<"UserPositions", 'String'>
  readonly outcome: Prisma.FieldRef<"UserPositions", 'String'>
  readonly outcomeIndex: Prisma.FieldRef<"UserPositions", 'Int'>
  readonly oppositeOutcome: Prisma.FieldRef<"UserPositions", 'String'>
  readonly oppositeAsset: Prisma.FieldRef<"UserPositions", 'String'>
  readonly endDate: Prisma.FieldRef<"UserPositions", 'DateTime'>
  readonly negativeRisk: Prisma.FieldRef<"UserPositions", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"UserPositions", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"UserPositions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserPositions findUnique
 */
export type UserPositionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter, which UserPositions to fetch.
   */
  where: Prisma.UserPositionsWhereUniqueInput
}

/**
 * UserPositions findUniqueOrThrow
 */
export type UserPositionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter, which UserPositions to fetch.
   */
  where: Prisma.UserPositionsWhereUniqueInput
}

/**
 * UserPositions findFirst
 */
export type UserPositionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter, which UserPositions to fetch.
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPositions to fetch.
   */
  orderBy?: Prisma.UserPositionsOrderByWithRelationInput | Prisma.UserPositionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPositions.
   */
  cursor?: Prisma.UserPositionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPositions.
   */
  distinct?: Prisma.UserPositionsScalarFieldEnum | Prisma.UserPositionsScalarFieldEnum[]
}

/**
 * UserPositions findFirstOrThrow
 */
export type UserPositionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter, which UserPositions to fetch.
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPositions to fetch.
   */
  orderBy?: Prisma.UserPositionsOrderByWithRelationInput | Prisma.UserPositionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPositions.
   */
  cursor?: Prisma.UserPositionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPositions.
   */
  distinct?: Prisma.UserPositionsScalarFieldEnum | Prisma.UserPositionsScalarFieldEnum[]
}

/**
 * UserPositions findMany
 */
export type UserPositionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter, which UserPositions to fetch.
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPositions to fetch.
   */
  orderBy?: Prisma.UserPositionsOrderByWithRelationInput | Prisma.UserPositionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserPositions.
   */
  cursor?: Prisma.UserPositionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPositions.
   */
  distinct?: Prisma.UserPositionsScalarFieldEnum | Prisma.UserPositionsScalarFieldEnum[]
}

/**
 * UserPositions create
 */
export type UserPositionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * The data needed to create a UserPositions.
   */
  data: Prisma.XOR<Prisma.UserPositionsCreateInput, Prisma.UserPositionsUncheckedCreateInput>
}

/**
 * UserPositions createMany
 */
export type UserPositionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserPositions.
   */
  data: Prisma.UserPositionsCreateManyInput | Prisma.UserPositionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserPositions createManyAndReturn
 */
export type UserPositionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * The data used to create many UserPositions.
   */
  data: Prisma.UserPositionsCreateManyInput | Prisma.UserPositionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserPositions update
 */
export type UserPositionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * The data needed to update a UserPositions.
   */
  data: Prisma.XOR<Prisma.UserPositionsUpdateInput, Prisma.UserPositionsUncheckedUpdateInput>
  /**
   * Choose, which UserPositions to update.
   */
  where: Prisma.UserPositionsWhereUniqueInput
}

/**
 * UserPositions updateMany
 */
export type UserPositionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserPositions.
   */
  data: Prisma.XOR<Prisma.UserPositionsUpdateManyMutationInput, Prisma.UserPositionsUncheckedUpdateManyInput>
  /**
   * Filter which UserPositions to update
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * Limit how many UserPositions to update.
   */
  limit?: number
}

/**
 * UserPositions updateManyAndReturn
 */
export type UserPositionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * The data used to update UserPositions.
   */
  data: Prisma.XOR<Prisma.UserPositionsUpdateManyMutationInput, Prisma.UserPositionsUncheckedUpdateManyInput>
  /**
   * Filter which UserPositions to update
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * Limit how many UserPositions to update.
   */
  limit?: number
}

/**
 * UserPositions upsert
 */
export type UserPositionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * The filter to search for the UserPositions to update in case it exists.
   */
  where: Prisma.UserPositionsWhereUniqueInput
  /**
   * In case the UserPositions found by the `where` argument doesn't exist, create a new UserPositions with this data.
   */
  create: Prisma.XOR<Prisma.UserPositionsCreateInput, Prisma.UserPositionsUncheckedCreateInput>
  /**
   * In case the UserPositions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserPositionsUpdateInput, Prisma.UserPositionsUncheckedUpdateInput>
}

/**
 * UserPositions delete
 */
export type UserPositionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
  /**
   * Filter which UserPositions to delete.
   */
  where: Prisma.UserPositionsWhereUniqueInput
}

/**
 * UserPositions deleteMany
 */
export type UserPositionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPositions to delete
   */
  where?: Prisma.UserPositionsWhereInput
  /**
   * Limit how many UserPositions to delete.
   */
  limit?: number
}

/**
 * UserPositions without action
 */
export type UserPositionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPositions
   */
  select?: Prisma.UserPositionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPositions
   */
  omit?: Prisma.UserPositionsOmit<ExtArgs> | null
}
