
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserActivities` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserActivities
 * 
 */
export type UserActivitiesModel = runtime.Types.Result.DefaultSelection<Prisma.$UserActivitiesPayload>

export type AggregateUserActivities = {
  _count: UserActivitiesCountAggregateOutputType | null
  _avg: UserActivitiesAvgAggregateOutputType | null
  _sum: UserActivitiesSumAggregateOutputType | null
  _min: UserActivitiesMinAggregateOutputType | null
  _max: UserActivitiesMaxAggregateOutputType | null
}

export type UserActivitiesAvgAggregateOutputType = {
  size: number | null
  usdcSize: number | null
  price: number | null
  outcomeIndex: number | null
  botExcutedTime: number | null
  myBoughtSize: number | null
}

export type UserActivitiesSumAggregateOutputType = {
  size: number | null
  usdcSize: number | null
  price: number | null
  outcomeIndex: number | null
  botExcutedTime: number | null
  myBoughtSize: number | null
}

export type UserActivitiesMinAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  icon: string | null
  name: string | null
  eventSlug: string | null
  proxyWallet: string | null
  conditionId: string | null
  type: string | null
  size: number | null
  usdcSize: number | null
  transactionHash: string | null
  price: number | null
  asset: string | null
  side: string | null
  outcomeIndex: number | null
  outcome: string | null
  pseudonym: string | null
  bio: string | null
  profileImage: string | null
  profileImageOptimized: string | null
  bot: boolean | null
  botExcutedTime: number | null
  myBoughtSize: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserActivitiesMaxAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  icon: string | null
  name: string | null
  eventSlug: string | null
  proxyWallet: string | null
  conditionId: string | null
  type: string | null
  size: number | null
  usdcSize: number | null
  transactionHash: string | null
  price: number | null
  asset: string | null
  side: string | null
  outcomeIndex: number | null
  outcome: string | null
  pseudonym: string | null
  bio: string | null
  profileImage: string | null
  profileImageOptimized: string | null
  bot: boolean | null
  botExcutedTime: number | null
  myBoughtSize: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserActivitiesCountAggregateOutputType = {
  id: number
  title: number
  slug: number
  icon: number
  name: number
  eventSlug: number
  proxyWallet: number
  conditionId: number
  type: number
  size: number
  usdcSize: number
  transactionHash: number
  price: number
  asset: number
  side: number
  outcomeIndex: number
  outcome: number
  pseudonym: number
  bio: number
  profileImage: number
  profileImageOptimized: number
  bot: number
  botExcutedTime: number
  myBoughtSize: number
  created_at: number
  updated_at: number
  _all: number
}


export type UserActivitiesAvgAggregateInputType = {
  size?: true
  usdcSize?: true
  price?: true
  outcomeIndex?: true
  botExcutedTime?: true
  myBoughtSize?: true
}

export type UserActivitiesSumAggregateInputType = {
  size?: true
  usdcSize?: true
  price?: true
  outcomeIndex?: true
  botExcutedTime?: true
  myBoughtSize?: true
}

export type UserActivitiesMinAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  name?: true
  eventSlug?: true
  proxyWallet?: true
  conditionId?: true
  type?: true
  size?: true
  usdcSize?: true
  transactionHash?: true
  price?: true
  asset?: true
  side?: true
  outcomeIndex?: true
  outcome?: true
  pseudonym?: true
  bio?: true
  profileImage?: true
  profileImageOptimized?: true
  bot?: true
  botExcutedTime?: true
  myBoughtSize?: true
  created_at?: true
  updated_at?: true
}

export type UserActivitiesMaxAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  name?: true
  eventSlug?: true
  proxyWallet?: true
  conditionId?: true
  type?: true
  size?: true
  usdcSize?: true
  transactionHash?: true
  price?: true
  asset?: true
  side?: true
  outcomeIndex?: true
  outcome?: true
  pseudonym?: true
  bio?: true
  profileImage?: true
  profileImageOptimized?: true
  bot?: true
  botExcutedTime?: true
  myBoughtSize?: true
  created_at?: true
  updated_at?: true
}

export type UserActivitiesCountAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  icon?: true
  name?: true
  eventSlug?: true
  proxyWallet?: true
  conditionId?: true
  type?: true
  size?: true
  usdcSize?: true
  transactionHash?: true
  price?: true
  asset?: true
  side?: true
  outcomeIndex?: true
  outcome?: true
  pseudonym?: true
  bio?: true
  profileImage?: true
  profileImageOptimized?: true
  bot?: true
  botExcutedTime?: true
  myBoughtSize?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type UserActivitiesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserActivities to aggregate.
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActivities to fetch.
   */
  orderBy?: Prisma.UserActivitiesOrderByWithRelationInput | Prisma.UserActivitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserActivitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActivities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActivities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserActivities
  **/
  _count?: true | UserActivitiesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserActivitiesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserActivitiesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserActivitiesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserActivitiesMaxAggregateInputType
}

export type GetUserActivitiesAggregateType<T extends UserActivitiesAggregateArgs> = {
      [P in keyof T & keyof AggregateUserActivities]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserActivities[P]>
    : Prisma.GetScalarType<T[P], AggregateUserActivities[P]>
}




export type UserActivitiesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserActivitiesWhereInput
  orderBy?: Prisma.UserActivitiesOrderByWithAggregationInput | Prisma.UserActivitiesOrderByWithAggregationInput[]
  by: Prisma.UserActivitiesScalarFieldEnum[] | Prisma.UserActivitiesScalarFieldEnum
  having?: Prisma.UserActivitiesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserActivitiesCountAggregateInputType | true
  _avg?: UserActivitiesAvgAggregateInputType
  _sum?: UserActivitiesSumAggregateInputType
  _min?: UserActivitiesMinAggregateInputType
  _max?: UserActivitiesMaxAggregateInputType
}

export type UserActivitiesGroupByOutputType = {
  id: string
  title: string | null
  slug: string | null
  icon: string | null
  name: string | null
  eventSlug: string | null
  proxyWallet: string | null
  conditionId: string | null
  type: string | null
  size: number | null
  usdcSize: number | null
  transactionHash: string | null
  price: number | null
  asset: string | null
  side: string | null
  outcomeIndex: number | null
  outcome: string | null
  pseudonym: string | null
  bio: string | null
  profileImage: string | null
  profileImageOptimized: string | null
  bot: boolean
  botExcutedTime: number | null
  myBoughtSize: number | null
  created_at: Date
  updated_at: Date
  _count: UserActivitiesCountAggregateOutputType | null
  _avg: UserActivitiesAvgAggregateOutputType | null
  _sum: UserActivitiesSumAggregateOutputType | null
  _min: UserActivitiesMinAggregateOutputType | null
  _max: UserActivitiesMaxAggregateOutputType | null
}

type GetUserActivitiesGroupByPayload<T extends UserActivitiesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserActivitiesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserActivitiesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserActivitiesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserActivitiesGroupByOutputType[P]>
      }
    >
  >



export type UserActivitiesWhereInput = {
  AND?: Prisma.UserActivitiesWhereInput | Prisma.UserActivitiesWhereInput[]
  OR?: Prisma.UserActivitiesWhereInput[]
  NOT?: Prisma.UserActivitiesWhereInput | Prisma.UserActivitiesWhereInput[]
  id?: Prisma.StringFilter<"UserActivities"> | string
  title?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  slug?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  icon?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  name?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  eventSlug?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  proxyWallet?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  conditionId?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  type?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  size?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  usdcSize?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  transactionHash?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  price?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  asset?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  side?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  outcomeIndex?: Prisma.IntNullableFilter<"UserActivities"> | number | null
  outcome?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  pseudonym?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  bio?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  profileImage?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  profileImageOptimized?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  bot?: Prisma.BoolFilter<"UserActivities"> | boolean
  botExcutedTime?: Prisma.IntNullableFilter<"UserActivities"> | number | null
  myBoughtSize?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  created_at?: Prisma.DateTimeFilter<"UserActivities"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserActivities"> | Date | string
}

export type UserActivitiesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  eventSlug?: Prisma.SortOrderInput | Prisma.SortOrder
  proxyWallet?: Prisma.SortOrderInput | Prisma.SortOrder
  conditionId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  usdcSize?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionHash?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  asset?: Prisma.SortOrderInput | Prisma.SortOrder
  side?: Prisma.SortOrderInput | Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  pseudonym?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImageOptimized?: Prisma.SortOrderInput | Prisma.SortOrder
  bot?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserActivitiesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserActivitiesWhereInput | Prisma.UserActivitiesWhereInput[]
  OR?: Prisma.UserActivitiesWhereInput[]
  NOT?: Prisma.UserActivitiesWhereInput | Prisma.UserActivitiesWhereInput[]
  title?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  slug?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  icon?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  name?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  eventSlug?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  proxyWallet?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  conditionId?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  type?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  size?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  usdcSize?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  transactionHash?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  price?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  asset?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  side?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  outcomeIndex?: Prisma.IntNullableFilter<"UserActivities"> | number | null
  outcome?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  pseudonym?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  bio?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  profileImage?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  profileImageOptimized?: Prisma.StringNullableFilter<"UserActivities"> | string | null
  bot?: Prisma.BoolFilter<"UserActivities"> | boolean
  botExcutedTime?: Prisma.IntNullableFilter<"UserActivities"> | number | null
  myBoughtSize?: Prisma.FloatNullableFilter<"UserActivities"> | number | null
  created_at?: Prisma.DateTimeFilter<"UserActivities"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserActivities"> | Date | string
}, "id">

export type UserActivitiesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  slug?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  eventSlug?: Prisma.SortOrderInput | Prisma.SortOrder
  proxyWallet?: Prisma.SortOrderInput | Prisma.SortOrder
  conditionId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  usdcSize?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionHash?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  asset?: Prisma.SortOrderInput | Prisma.SortOrder
  side?: Prisma.SortOrderInput | Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  pseudonym?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImageOptimized?: Prisma.SortOrderInput | Prisma.SortOrder
  bot?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.UserActivitiesCountOrderByAggregateInput
  _avg?: Prisma.UserActivitiesAvgOrderByAggregateInput
  _max?: Prisma.UserActivitiesMaxOrderByAggregateInput
  _min?: Prisma.UserActivitiesMinOrderByAggregateInput
  _sum?: Prisma.UserActivitiesSumOrderByAggregateInput
}

export type UserActivitiesScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserActivitiesScalarWhereWithAggregatesInput | Prisma.UserActivitiesScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserActivitiesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserActivitiesScalarWhereWithAggregatesInput | Prisma.UserActivitiesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserActivities"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  slug?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  icon?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  eventSlug?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  proxyWallet?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  conditionId?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  type?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  size?: Prisma.FloatNullableWithAggregatesFilter<"UserActivities"> | number | null
  usdcSize?: Prisma.FloatNullableWithAggregatesFilter<"UserActivities"> | number | null
  transactionHash?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  price?: Prisma.FloatNullableWithAggregatesFilter<"UserActivities"> | number | null
  asset?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  side?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  outcomeIndex?: Prisma.IntNullableWithAggregatesFilter<"UserActivities"> | number | null
  outcome?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  pseudonym?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  bio?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  profileImage?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  profileImageOptimized?: Prisma.StringNullableWithAggregatesFilter<"UserActivities"> | string | null
  bot?: Prisma.BoolWithAggregatesFilter<"UserActivities"> | boolean
  botExcutedTime?: Prisma.IntNullableWithAggregatesFilter<"UserActivities"> | number | null
  myBoughtSize?: Prisma.FloatNullableWithAggregatesFilter<"UserActivities"> | number | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"UserActivities"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"UserActivities"> | Date | string
}

export type UserActivitiesCreateInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  name?: string | null
  eventSlug?: string | null
  proxyWallet?: string | null
  conditionId?: string | null
  type?: string | null
  size?: number | null
  usdcSize?: number | null
  transactionHash?: string | null
  price?: number | null
  asset?: string | null
  side?: string | null
  outcomeIndex?: number | null
  outcome?: string | null
  pseudonym?: string | null
  bio?: string | null
  profileImage?: string | null
  profileImageOptimized?: string | null
  bot?: boolean
  botExcutedTime?: number | null
  myBoughtSize?: number | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserActivitiesUncheckedCreateInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  name?: string | null
  eventSlug?: string | null
  proxyWallet?: string | null
  conditionId?: string | null
  type?: string | null
  size?: number | null
  usdcSize?: number | null
  transactionHash?: string | null
  price?: number | null
  asset?: string | null
  side?: string | null
  outcomeIndex?: number | null
  outcome?: string | null
  pseudonym?: string | null
  bio?: string | null
  profileImage?: string | null
  profileImageOptimized?: string | null
  bot?: boolean
  botExcutedTime?: number | null
  myBoughtSize?: number | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserActivitiesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  usdcSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  transactionHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  asset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  side?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pseudonym?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImageOptimized?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  botExcutedTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  myBoughtSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActivitiesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  usdcSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  transactionHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  asset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  side?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pseudonym?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImageOptimized?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  botExcutedTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  myBoughtSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActivitiesCreateManyInput = {
  id?: string
  title?: string | null
  slug?: string | null
  icon?: string | null
  name?: string | null
  eventSlug?: string | null
  proxyWallet?: string | null
  conditionId?: string | null
  type?: string | null
  size?: number | null
  usdcSize?: number | null
  transactionHash?: string | null
  price?: number | null
  asset?: string | null
  side?: string | null
  outcomeIndex?: number | null
  outcome?: string | null
  pseudonym?: string | null
  bio?: string | null
  profileImage?: string | null
  profileImageOptimized?: string | null
  bot?: boolean
  botExcutedTime?: number | null
  myBoughtSize?: number | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserActivitiesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  usdcSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  transactionHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  asset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  side?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pseudonym?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImageOptimized?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  botExcutedTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  myBoughtSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActivitiesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  slug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventSlug?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proxyWallet?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conditionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  usdcSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  transactionHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  asset?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  side?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcomeIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pseudonym?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImageOptimized?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  botExcutedTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  myBoughtSize?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActivitiesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  name?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  size?: Prisma.SortOrder
  usdcSize?: Prisma.SortOrder
  transactionHash?: Prisma.SortOrder
  price?: Prisma.SortOrder
  asset?: Prisma.SortOrder
  side?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  pseudonym?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  profileImageOptimized?: Prisma.SortOrder
  bot?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserActivitiesAvgOrderByAggregateInput = {
  size?: Prisma.SortOrder
  usdcSize?: Prisma.SortOrder
  price?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrder
}

export type UserActivitiesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  name?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  size?: Prisma.SortOrder
  usdcSize?: Prisma.SortOrder
  transactionHash?: Prisma.SortOrder
  price?: Prisma.SortOrder
  asset?: Prisma.SortOrder
  side?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  pseudonym?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  profileImageOptimized?: Prisma.SortOrder
  bot?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserActivitiesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  name?: Prisma.SortOrder
  eventSlug?: Prisma.SortOrder
  proxyWallet?: Prisma.SortOrder
  conditionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  size?: Prisma.SortOrder
  usdcSize?: Prisma.SortOrder
  transactionHash?: Prisma.SortOrder
  price?: Prisma.SortOrder
  asset?: Prisma.SortOrder
  side?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  pseudonym?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  profileImageOptimized?: Prisma.SortOrder
  bot?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserActivitiesSumOrderByAggregateInput = {
  size?: Prisma.SortOrder
  usdcSize?: Prisma.SortOrder
  price?: Prisma.SortOrder
  outcomeIndex?: Prisma.SortOrder
  botExcutedTime?: Prisma.SortOrder
  myBoughtSize?: Prisma.SortOrder
}



export type UserActivitiesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  name?: boolean
  eventSlug?: boolean
  proxyWallet?: boolean
  conditionId?: boolean
  type?: boolean
  size?: boolean
  usdcSize?: boolean
  transactionHash?: boolean
  price?: boolean
  asset?: boolean
  side?: boolean
  outcomeIndex?: boolean
  outcome?: boolean
  pseudonym?: boolean
  bio?: boolean
  profileImage?: boolean
  profileImageOptimized?: boolean
  bot?: boolean
  botExcutedTime?: boolean
  myBoughtSize?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userActivities"]>

export type UserActivitiesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  name?: boolean
  eventSlug?: boolean
  proxyWallet?: boolean
  conditionId?: boolean
  type?: boolean
  size?: boolean
  usdcSize?: boolean
  transactionHash?: boolean
  price?: boolean
  asset?: boolean
  side?: boolean
  outcomeIndex?: boolean
  outcome?: boolean
  pseudonym?: boolean
  bio?: boolean
  profileImage?: boolean
  profileImageOptimized?: boolean
  bot?: boolean
  botExcutedTime?: boolean
  myBoughtSize?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userActivities"]>

export type UserActivitiesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  name?: boolean
  eventSlug?: boolean
  proxyWallet?: boolean
  conditionId?: boolean
  type?: boolean
  size?: boolean
  usdcSize?: boolean
  transactionHash?: boolean
  price?: boolean
  asset?: boolean
  side?: boolean
  outcomeIndex?: boolean
  outcome?: boolean
  pseudonym?: boolean
  bio?: boolean
  profileImage?: boolean
  profileImageOptimized?: boolean
  bot?: boolean
  botExcutedTime?: boolean
  myBoughtSize?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userActivities"]>

export type UserActivitiesSelectScalar = {
  id?: boolean
  title?: boolean
  slug?: boolean
  icon?: boolean
  name?: boolean
  eventSlug?: boolean
  proxyWallet?: boolean
  conditionId?: boolean
  type?: boolean
  size?: boolean
  usdcSize?: boolean
  transactionHash?: boolean
  price?: boolean
  asset?: boolean
  side?: boolean
  outcomeIndex?: boolean
  outcome?: boolean
  pseudonym?: boolean
  bio?: boolean
  profileImage?: boolean
  profileImageOptimized?: boolean
  bot?: boolean
  botExcutedTime?: boolean
  myBoughtSize?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type UserActivitiesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "slug" | "icon" | "name" | "eventSlug" | "proxyWallet" | "conditionId" | "type" | "size" | "usdcSize" | "transactionHash" | "price" | "asset" | "side" | "outcomeIndex" | "outcome" | "pseudonym" | "bio" | "profileImage" | "profileImageOptimized" | "bot" | "botExcutedTime" | "myBoughtSize" | "created_at" | "updated_at", ExtArgs["result"]["userActivities"]>

export type $UserActivitiesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserActivities"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string | null
    slug: string | null
    icon: string | null
    name: string | null
    eventSlug: string | null
    proxyWallet: string | null
    conditionId: string | null
    type: string | null
    size: number | null
    usdcSize: number | null
    transactionHash: string | null
    price: number | null
    asset: string | null
    side: string | null
    outcomeIndex: number | null
    outcome: string | null
    pseudonym: string | null
    bio: string | null
    profileImage: string | null
    profileImageOptimized: string | null
    bot: boolean
    botExcutedTime: number | null
    myBoughtSize: number | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["userActivities"]>
  composites: {}
}

export type UserActivitiesGetPayload<S extends boolean | null | undefined | UserActivitiesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload, S>

export type UserActivitiesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserActivitiesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserActivitiesCountAggregateInputType | true
  }

export interface UserActivitiesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserActivities'], meta: { name: 'UserActivities' } }
  /**
   * Find zero or one UserActivities that matches the filter.
   * @param {UserActivitiesFindUniqueArgs} args - Arguments to find a UserActivities
   * @example
   * // Get one UserActivities
   * const userActivities = await prisma.userActivities.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserActivitiesFindUniqueArgs>(args: Prisma.SelectSubset<T, UserActivitiesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserActivities that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserActivitiesFindUniqueOrThrowArgs} args - Arguments to find a UserActivities
   * @example
   * // Get one UserActivities
   * const userActivities = await prisma.userActivities.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserActivitiesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserActivitiesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserActivities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesFindFirstArgs} args - Arguments to find a UserActivities
   * @example
   * // Get one UserActivities
   * const userActivities = await prisma.userActivities.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserActivitiesFindFirstArgs>(args?: Prisma.SelectSubset<T, UserActivitiesFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserActivities that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesFindFirstOrThrowArgs} args - Arguments to find a UserActivities
   * @example
   * // Get one UserActivities
   * const userActivities = await prisma.userActivities.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserActivitiesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserActivitiesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserActivities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserActivities
   * const userActivities = await prisma.userActivities.findMany()
   * 
   * // Get first 10 UserActivities
   * const userActivities = await prisma.userActivities.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userActivitiesWithIdOnly = await prisma.userActivities.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserActivitiesFindManyArgs>(args?: Prisma.SelectSubset<T, UserActivitiesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserActivities.
   * @param {UserActivitiesCreateArgs} args - Arguments to create a UserActivities.
   * @example
   * // Create one UserActivities
   * const UserActivities = await prisma.userActivities.create({
   *   data: {
   *     // ... data to create a UserActivities
   *   }
   * })
   * 
   */
  create<T extends UserActivitiesCreateArgs>(args: Prisma.SelectSubset<T, UserActivitiesCreateArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserActivities.
   * @param {UserActivitiesCreateManyArgs} args - Arguments to create many UserActivities.
   * @example
   * // Create many UserActivities
   * const userActivities = await prisma.userActivities.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserActivitiesCreateManyArgs>(args?: Prisma.SelectSubset<T, UserActivitiesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserActivities and returns the data saved in the database.
   * @param {UserActivitiesCreateManyAndReturnArgs} args - Arguments to create many UserActivities.
   * @example
   * // Create many UserActivities
   * const userActivities = await prisma.userActivities.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserActivities and only return the `id`
   * const userActivitiesWithIdOnly = await prisma.userActivities.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserActivitiesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserActivitiesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserActivities.
   * @param {UserActivitiesDeleteArgs} args - Arguments to delete one UserActivities.
   * @example
   * // Delete one UserActivities
   * const UserActivities = await prisma.userActivities.delete({
   *   where: {
   *     // ... filter to delete one UserActivities
   *   }
   * })
   * 
   */
  delete<T extends UserActivitiesDeleteArgs>(args: Prisma.SelectSubset<T, UserActivitiesDeleteArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserActivities.
   * @param {UserActivitiesUpdateArgs} args - Arguments to update one UserActivities.
   * @example
   * // Update one UserActivities
   * const userActivities = await prisma.userActivities.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserActivitiesUpdateArgs>(args: Prisma.SelectSubset<T, UserActivitiesUpdateArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserActivities.
   * @param {UserActivitiesDeleteManyArgs} args - Arguments to filter UserActivities to delete.
   * @example
   * // Delete a few UserActivities
   * const { count } = await prisma.userActivities.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserActivitiesDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserActivitiesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserActivities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserActivities
   * const userActivities = await prisma.userActivities.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserActivitiesUpdateManyArgs>(args: Prisma.SelectSubset<T, UserActivitiesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserActivities and returns the data updated in the database.
   * @param {UserActivitiesUpdateManyAndReturnArgs} args - Arguments to update many UserActivities.
   * @example
   * // Update many UserActivities
   * const userActivities = await prisma.userActivities.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserActivities and only return the `id`
   * const userActivitiesWithIdOnly = await prisma.userActivities.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserActivitiesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserActivitiesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserActivities.
   * @param {UserActivitiesUpsertArgs} args - Arguments to update or create a UserActivities.
   * @example
   * // Update or create a UserActivities
   * const userActivities = await prisma.userActivities.upsert({
   *   create: {
   *     // ... data to create a UserActivities
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserActivities we want to update
   *   }
   * })
   */
  upsert<T extends UserActivitiesUpsertArgs>(args: Prisma.SelectSubset<T, UserActivitiesUpsertArgs<ExtArgs>>): Prisma.Prisma__UserActivitiesClient<runtime.Types.Result.GetResult<Prisma.$UserActivitiesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserActivities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesCountArgs} args - Arguments to filter UserActivities to count.
   * @example
   * // Count the number of UserActivities
   * const count = await prisma.userActivities.count({
   *   where: {
   *     // ... the filter for the UserActivities we want to count
   *   }
   * })
  **/
  count<T extends UserActivitiesCountArgs>(
    args?: Prisma.Subset<T, UserActivitiesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserActivitiesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserActivities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserActivitiesAggregateArgs>(args: Prisma.Subset<T, UserActivitiesAggregateArgs>): Prisma.PrismaPromise<GetUserActivitiesAggregateType<T>>

  /**
   * Group by UserActivities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActivitiesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserActivitiesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserActivitiesGroupByArgs['orderBy'] }
      : { orderBy?: UserActivitiesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserActivitiesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserActivitiesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserActivities model
 */
readonly fields: UserActivitiesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserActivities.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserActivitiesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserActivities model
 */
export interface UserActivitiesFieldRefs {
  readonly id: Prisma.FieldRef<"UserActivities", 'String'>
  readonly title: Prisma.FieldRef<"UserActivities", 'String'>
  readonly slug: Prisma.FieldRef<"UserActivities", 'String'>
  readonly icon: Prisma.FieldRef<"UserActivities", 'String'>
  readonly name: Prisma.FieldRef<"UserActivities", 'String'>
  readonly eventSlug: Prisma.FieldRef<"UserActivities", 'String'>
  readonly proxyWallet: Prisma.FieldRef<"UserActivities", 'String'>
  readonly conditionId: Prisma.FieldRef<"UserActivities", 'String'>
  readonly type: Prisma.FieldRef<"UserActivities", 'String'>
  readonly size: Prisma.FieldRef<"UserActivities", 'Float'>
  readonly usdcSize: Prisma.FieldRef<"UserActivities", 'Float'>
  readonly transactionHash: Prisma.FieldRef<"UserActivities", 'String'>
  readonly price: Prisma.FieldRef<"UserActivities", 'Float'>
  readonly asset: Prisma.FieldRef<"UserActivities", 'String'>
  readonly side: Prisma.FieldRef<"UserActivities", 'String'>
  readonly outcomeIndex: Prisma.FieldRef<"UserActivities", 'Int'>
  readonly outcome: Prisma.FieldRef<"UserActivities", 'String'>
  readonly pseudonym: Prisma.FieldRef<"UserActivities", 'String'>
  readonly bio: Prisma.FieldRef<"UserActivities", 'String'>
  readonly profileImage: Prisma.FieldRef<"UserActivities", 'String'>
  readonly profileImageOptimized: Prisma.FieldRef<"UserActivities", 'String'>
  readonly bot: Prisma.FieldRef<"UserActivities", 'Boolean'>
  readonly botExcutedTime: Prisma.FieldRef<"UserActivities", 'Int'>
  readonly myBoughtSize: Prisma.FieldRef<"UserActivities", 'Float'>
  readonly created_at: Prisma.FieldRef<"UserActivities", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"UserActivities", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserActivities findUnique
 */
export type UserActivitiesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter, which UserActivities to fetch.
   */
  where: Prisma.UserActivitiesWhereUniqueInput
}

/**
 * UserActivities findUniqueOrThrow
 */
export type UserActivitiesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter, which UserActivities to fetch.
   */
  where: Prisma.UserActivitiesWhereUniqueInput
}

/**
 * UserActivities findFirst
 */
export type UserActivitiesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter, which UserActivities to fetch.
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActivities to fetch.
   */
  orderBy?: Prisma.UserActivitiesOrderByWithRelationInput | Prisma.UserActivitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserActivities.
   */
  cursor?: Prisma.UserActivitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActivities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActivities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActivities.
   */
  distinct?: Prisma.UserActivitiesScalarFieldEnum | Prisma.UserActivitiesScalarFieldEnum[]
}

/**
 * UserActivities findFirstOrThrow
 */
export type UserActivitiesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter, which UserActivities to fetch.
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActivities to fetch.
   */
  orderBy?: Prisma.UserActivitiesOrderByWithRelationInput | Prisma.UserActivitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserActivities.
   */
  cursor?: Prisma.UserActivitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActivities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActivities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActivities.
   */
  distinct?: Prisma.UserActivitiesScalarFieldEnum | Prisma.UserActivitiesScalarFieldEnum[]
}

/**
 * UserActivities findMany
 */
export type UserActivitiesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter, which UserActivities to fetch.
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActivities to fetch.
   */
  orderBy?: Prisma.UserActivitiesOrderByWithRelationInput | Prisma.UserActivitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserActivities.
   */
  cursor?: Prisma.UserActivitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActivities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActivities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActivities.
   */
  distinct?: Prisma.UserActivitiesScalarFieldEnum | Prisma.UserActivitiesScalarFieldEnum[]
}

/**
 * UserActivities create
 */
export type UserActivitiesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * The data needed to create a UserActivities.
   */
  data: Prisma.XOR<Prisma.UserActivitiesCreateInput, Prisma.UserActivitiesUncheckedCreateInput>
}

/**
 * UserActivities createMany
 */
export type UserActivitiesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserActivities.
   */
  data: Prisma.UserActivitiesCreateManyInput | Prisma.UserActivitiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserActivities createManyAndReturn
 */
export type UserActivitiesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * The data used to create many UserActivities.
   */
  data: Prisma.UserActivitiesCreateManyInput | Prisma.UserActivitiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserActivities update
 */
export type UserActivitiesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * The data needed to update a UserActivities.
   */
  data: Prisma.XOR<Prisma.UserActivitiesUpdateInput, Prisma.UserActivitiesUncheckedUpdateInput>
  /**
   * Choose, which UserActivities to update.
   */
  where: Prisma.UserActivitiesWhereUniqueInput
}

/**
 * UserActivities updateMany
 */
export type UserActivitiesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserActivities.
   */
  data: Prisma.XOR<Prisma.UserActivitiesUpdateManyMutationInput, Prisma.UserActivitiesUncheckedUpdateManyInput>
  /**
   * Filter which UserActivities to update
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * Limit how many UserActivities to update.
   */
  limit?: number
}

/**
 * UserActivities updateManyAndReturn
 */
export type UserActivitiesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * The data used to update UserActivities.
   */
  data: Prisma.XOR<Prisma.UserActivitiesUpdateManyMutationInput, Prisma.UserActivitiesUncheckedUpdateManyInput>
  /**
   * Filter which UserActivities to update
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * Limit how many UserActivities to update.
   */
  limit?: number
}

/**
 * UserActivities upsert
 */
export type UserActivitiesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * The filter to search for the UserActivities to update in case it exists.
   */
  where: Prisma.UserActivitiesWhereUniqueInput
  /**
   * In case the UserActivities found by the `where` argument doesn't exist, create a new UserActivities with this data.
   */
  create: Prisma.XOR<Prisma.UserActivitiesCreateInput, Prisma.UserActivitiesUncheckedCreateInput>
  /**
   * In case the UserActivities was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserActivitiesUpdateInput, Prisma.UserActivitiesUncheckedUpdateInput>
}

/**
 * UserActivities delete
 */
export type UserActivitiesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
  /**
   * Filter which UserActivities to delete.
   */
  where: Prisma.UserActivitiesWhereUniqueInput
}

/**
 * UserActivities deleteMany
 */
export type UserActivitiesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserActivities to delete
   */
  where?: Prisma.UserActivitiesWhereInput
  /**
   * Limit how many UserActivities to delete.
   */
  limit?: number
}

/**
 * UserActivities without action
 */
export type UserActivitiesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActivities
   */
  select?: Prisma.UserActivitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActivities
   */
  omit?: Prisma.UserActivitiesOmit<ExtArgs> | null
}
