module.exports = {
  apps: [
    {
      name: 'copy-bot-poly',
      script: 'dist/index.js',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/copy-bot-poly/copy-bot-poly-error.log',
      out_file: '/var/log/copy-bot-poly/copy-bot-poly-output.log',
      merge_logs: true,
      log_type: 'raw',
      node_args: '--max-old-space-size=1024 --enable-source-maps',
    },
    {
      name: 'copy-bot-close-stale',
      script: 'dist/scripts/closeStalePositions.js',
      cron_restart: '*/15 * * * *',
      autorestart: false,
      watch: false,
      kill_timeout: 300000,
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/copy-bot-close-stale/close-stale-error.log',
      out_file: '/var/log/copy-bot-close-stale/close-stale-output.log',
      merge_logs: true,
      node_args: '--enable-source-maps',
    },
    {
      name: 'copy-bot-close-resolved',
      script: 'dist/scripts/closeResolvedPositions.js',
      cron_restart: '*/30 * * * *',
      autorestart: false,
      watch: false,
      kill_timeout: 600000,
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/copy-bot-close-resolved/close-resolved-error.log',
      out_file: '/var/log/copy-bot-close-resolved/close-resolved-output.log',
      merge_logs: true,
      node_args: '--enable-source-maps',
    },
    {
      name: 'copy-bot-redeem',
      script: 'dist/scripts/redeemResolvedPositions.js',
      cron_restart: '7,22,37,52 * * * *',
      autorestart: false,
      watch: false,
      kill_timeout: 600000,
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/copy-bot-redeem/redeem-error.log',
      out_file: '/var/log/copy-bot-redeem/redeem-output.log',
      merge_logs: true,

      node_args: '--enable-source-maps',
    },
  ],
};
