
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  UserPositions: 'UserPositions',
  UserActivities: 'UserActivities',
  Config: 'Config'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserPositionsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  icon: 'icon',
  proxyWallet: 'proxyWallet',
  assets: 'assets',
  conditionId: 'conditionId',
  size: 'size',
  avgPrice: 'avgPrice',
  initialValue: 'initialValue',
  currentValue: 'currentValue',
  cashPnl: 'cashPnl',
  percentPnl: 'percentPnl',
  totalBought: 'totalBought',
  realizedPnl: 'realizedPnl',
  percentRealizedPnl: 'percentRealizedPnl',
  curPrice: 'curPrice',
  redeemable: 'redeemable',
  mergeable: 'mergeable',
  eventSlug: 'eventSlug',
  outcome: 'outcome',
  outcomeIndex: 'outcomeIndex',
  oppositeOutcome: 'oppositeOutcome',
  oppositeAsset: 'oppositeAsset',
  endDate: 'endDate',
  negativeRisk: 'negativeRisk',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserPositionsScalarFieldEnum = (typeof UserPositionsScalarFieldEnum)[keyof typeof UserPositionsScalarFieldEnum]


export const UserActivitiesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  icon: 'icon',
  name: 'name',
  eventSlug: 'eventSlug',
  proxyWallet: 'proxyWallet',
  conditionId: 'conditionId',
  type: 'type',
  size: 'size',
  usdcSize: 'usdcSize',
  transactionHash: 'transactionHash',
  price: 'price',
  asset: 'asset',
  side: 'side',
  outcomeIndex: 'outcomeIndex',
  outcome: 'outcome',
  pseudonym: 'pseudonym',
  bio: 'bio',
  profileImage: 'profileImage',
  profileImageOptimized: 'profileImageOptimized',
  bot: 'bot',
  botExcutedTime: 'botExcutedTime',
  myBoughtSize: 'myBoughtSize',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserActivitiesScalarFieldEnum = (typeof UserActivitiesScalarFieldEnum)[keyof typeof UserActivitiesScalarFieldEnum]


export const ConfigScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ConfigScalarFieldEnum = (typeof ConfigScalarFieldEnum)[keyof typeof ConfigScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

